### ISSUE TITLE
Unistalling it crashed my P10 lite

### ISSUE THREAD

**Issue by Harlock1978** [Magisk-Modules-Repo/riru-core#2]
I disabled riru-core and riru edexposed to see if this would have helped not connecting to my bank app, but after that my phone is not working anymore.
I have no home or I cannot receive phone call.

I had to do a factory reset to restart using my phone

**Comment by RikkaW** [comment]
Anything could happen when you use Xposed. It's highly possible that your problem is not related to Riru itself.
